trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Azcheck

jobs:
- job: BuildAndPackage
  displayName: 'Build and Package Java Application'
  steps:
  - checkout: self

  - script: |
      # Set environment variables (assuming you have these variables in the variable group)
      export DB_URL=$(VG_DB_URL)
      export DB_USERNAME=$(VG_DB_USERNAME)
      export DB_PASSWORD=$(VG_DB_PASSWORD)

      echo "check=${DB_URL}"
      echo "check=${DB_USERNAME}"
      echo "check=${DB_PASSWORD}"

      # Replace placeholders in application.properties with environment variables
      sed -i "s|{{jdbc:mysql://\${MYSQL_HOST:localhost}:\${MYSQL_PORT:3306}}}|$DB_URL|g" src/main/resources/application.properties
      sed -i "s|{{MYSQL_USER:root}}|$DB_USERNAME|g" src/main/resources/application.properties
      sed -i "s|{{MYSQL_PASSWORD:Changepond@123}}|$DB_PASSWORD|g" src/main/resources/application.properties
    displayName: 'Replace placeholders in application.properties'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-DskipTests'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - script: |
      # Create a zip file from the contents of the target folder
      cd target
      zip -r ../JavaApp.zip .

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/JavaApp.zip'
      artifactName: 'JavaApp'
      publishLocation: 'container'
    displayName: 'Publish Artifact'
