trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
- group: Azcheck


jobs:
- job: BuildAndPackage
  displayName: 'Build and Package Java Application'
  steps:
  - checkout: self

  - script: |
      # Set environment variables
      export DB_URL="jdbc:mysql://$(MYSQL_HOST:localhost):$(MYSQL_PORT:3306)"
      export DB_USERNAME="$(MYSQL_USER:root)"
      export DB_PASSWORD="$(MYSQL_PASSWORD:Changepond@123)"

      # Replace placeholders in application.properties with environment variables
      sed -i "s|{{jdbc:mysql://\${MYSQL_HOST:localhost}:\${MYSQL_PORT:3306}}}|$DB_URL|g" src/main/resources/application.properties
      sed -i "s|{{MYSQL_USER:root}}|$DB_USERNAME|g" src/main/resources/application.properties
      sed -i "s|{{MYSQL_PASSWORD:Changepond@123}}|$DB_PASSWORD|g" src/main/resources/application.properties
    displayName: 'Replace placeholders in application.properties'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-DskipTests'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'target'
      artifactName: 'JavaApp'
      publishLocation: 'container'
    displayName: 'Publish Artifact'
