trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndPackage
  displayName: 'Build and Package Java Application'
  steps:
  #- checkout: self

  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true

  - script: |
      # Replace placeholders in application.properties with environment variables
      sed -i "s|{{jdbc:mysql://\${MYSQL_HOST:localhost}:\${MYSQL_PORT:3306}}}|$(DB_URL)|g" src/main/resources/application.properties
      sed -i "s|{{MYSQL_USER:root}}|$(DB_USERNAME)|g" src/main/resources/application.properties
      sed -i "s|{{MYSQL_PASSWORD:Changepond@123}}|$(DB_PASSWORD)|g" src/main/resources/application.properties
      
      # Build the Java application
      ./mvnw clean package
    displayName: 'Build Java Application'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'target'
      artifactName: 'JavaApp'
      publishLocation: 'container'
    displayName: 'Publish Artifact'
